# https://pre-commit.com
# https://pre-commit.com/hooks.html

default_language_version:
  python: python3.6

repos:
  # Sort python import
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: "v4.3.21"
    hooks:
      - id: isort

  # Clean indentation / code style
  - repo: https://github.com/psf/black
    rev: "19.3b0"
    hooks:
      - id: black

  #
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v2.3.0"
    hooks:
#      - id: end-of-file-fixer
      - id: flake8

  # Check static types if set (var: type = value)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.761'
    # args: [--no-strict-optional, --ignore-missing-imports]
    hooks:
      - id: mypy

  # Update requirements.txt file
  - repo: https://github.com/atugushev/pip-tools
    rev: e33f07
    hooks:
      - id: pip-compile
